### ISSUE TITLE
Manual Opt In for Netlify: Trigger Manual Build 

### ISSUE THREAD

**Issue by akachru-github** [overture-stack/gitlify#1]
![Insights   Builds.png](https://images.zenhubusercontent.com/5d55b1b74d335f147c3e6dc0/b514f3db-0af9-48e6-9046-e1bfb5b7072a)

This ticket was created to allow Softeng to manualy opt in to Netlify builds rather than have them be built automatically. In Jan 2020, Netlify introduced a new payment scheme that reduces the build minutes allowed from unlimited to 300. In Dec 2019, we had used over 3000 build minutes. We are forced to take drastic action to reduce this down to only what we need. The solution proposed is to manually opt in on what is required. This will effect ALL TEAMS USING NETLIFY. 

- Add button to trigger manual build on Github.

**Comment by justincorrigible** [comment]
In first instance, I can confirm we can turn off entirely the automatic deployment, for we can trigger those manually using a webhook.

Sure it's extra effort, but will definitely encourage people be selective about their deployments.

It's triggered by making a POST call like this:
`https://api.netlify.com/build_hooks/<webhookID>?trigger_branch=<branchName>&trigger_title=Deployment+triggered+by+<developer>`

All params are optional, and if a branch name is not passed, Netlify will deploy the default branch for that repo.

**Comment by justincorrigible** [comment]
Initial implementation complete.
Published an initial beta version at https://www.npmjs.com/package/@overture-stack/gitlify
It comprises a CLI, which goes "gitlify <branchname>" and relies on two variables being set environmentally:
GITHUB_USER and NETLIFY_WEBHOOK.

We require a github user, in order to identify who's triggering a build. May include some validation later to ensure the user is actually the one logged in, and that they belongs to the organisation.

If testing is successful, we can proceed to deploying the package in the relevant repos, and then disabling automatic builds entirely for our Netlify account.
